version: '3.3'

services:
  redis:
    container_name: redis-stack
    image: redis/redis-stack:7.2.0-v6
    restart: on-failure
    ports:
      - '0.0.0.0:6379:6379'
      - '0.0.0.0:8001:8001'
    volumes:
      - cache:/data
      - redis-data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

volumes:
  redis-data:
  cache:
    driver: local
