version: '3.7'

services:

  qdrant:
    container_name: vector-store
    image: qdrant/qdrant:v1.6.1
    restart: on-failure
    ports:
      - '0.0.0.0:8888:8000'
      - '0.0.0.0:9999:6333'
    volumes:
      - cache:/data
      - qdrant:/qdrant/storage:z
      - ./config/:/qdrant/config/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:9999/healthz" ]
      interval: 200s
      timeout: 200s
      retries: 5

  redis:
    container_name: redis-stack
    image: redis/redis-stack:7.2.0-v6
    restart: on-failure
    ports:
      - '0.0.0.0:6379:6379'
      - '0.0.0.0:8001:8001'
    volumes:
      - cache:/data
      - redis-data:/var/lib/redis/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 200s
      timeout: 200s
      retries: 5

  streamlit:
    container_name: frontend
    image: sagesnippetapp:latest
    build: .
    working_dir: /app
    restart: on-failure
    ports:
      - '0.0.0.0:8501:8501'
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8051/_stcore/health"]
      interval: 200s
      timeout: 200s
      retries: 5
    depends_on:
      - redis
      - qdrant
    env_file:
      - prod.env

volumes:
  qdrant:
  redis-data:
  cache:
    driver: local
  config:
